wallpaper {
    monitor = DP-3
    path = ~/.local/wall-2.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = ~/.local/wall-1.png
    fit_mode = cover
}

wallpaper {
    monitor = 
    path = ~/.local/wall-0.png
    fit_mode = cover
}
