vim.g.mapleader = " "
vim.g.maplocalleader = " "
local builtin = require("telescope.builtin")
local rulelib = require("core.rulelib")
vim.keymap.set("n", "<leader>dn", function()
	require("core.diagnostics").toggle_diagnostics_noise()
end, { desc = "Toggle diagnostics noise" })

vim.keymap.set("t", "<esc><esc>", function()
	vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<c-\\><c-n>", true, false, true), "n", false)
end, { silent = true })
vim.keymap.set("n", "<leader>fmt", function()
	require("core.format").toggle_autoformat()
end, { desc = "Toggle Autoformating on save" })
vim.keymap.set("n", "-", "<cmd>Oil<cr>", { desc = "reload nvim config" })
vim.keymap.set("n", "<c-r>", rulelib.reload_config, { desc = "reload nvim config" })
vim.keymap.set("n", "<c-s>", ":w<cr>")
vim.keymap.set({ "n", "t" }, "<c-t>", vim.cmd.Custerm, { desc = "rulelib floating terminal" })
vim.keymap.set("n", "<c-f>", builtin.find_files, { desc = "find files" })
vim.keymap.set("n", "<leader>fo", rulelib.ts_picker(), { desc = "TS outline (overview)" })
vim.keymap.set("n", "<leader>rg", builtin.live_grep, { desc = "Live grep" })
vim.keymap.set("n", "<leader>fb", builtin.buffers, { desc = "Buffers" })
vim.keymap.set("n", "<leader>fh", builtin.help_tags, { desc = "Help" })
vim.keymap.set("n", "<leader>fr", builtin.oldfiles, { desc = "Recent files" })
