vim.g.mapleader = " "
vim.g.maplocalleader = " "
local builtin = require("telescope.builtin")
require("telescope").load_extension("harpoon")
local harpoon_ui = require("harpoon.ui")
local rulelib = require("core.rulelib")
vim.keymap.set("n", "<leader>dn", function()
	require("core.diagnostics").toggle_diagnostics_noise()
end, { desc = "Toggle diagnostics noise" })

vim.keymap.set("t", "<esc><esc>", function()
	vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<c-\\><c-n>", true, false, true), "n", false)
end, { silent = true })
vim.keymap.set("n", "<leader>fmt", function()
	require("core.format").toggle_autoformat()
end, { desc = "Toggle Autoformating on save" })
vim.keymap.set("n", "-", "<cmd>Oil<cr>", { desc = "reload nvim config" })
vim.keymap.set("n", "<c-s>", ":w<cr>")
vim.keymap.set("n", "<leader>v", ":vsplit<cr>")
vim.keymap.set({ "n", "t" }, "<c-t>", vim.cmd.Custerm, { desc = "rulelib floating terminal" })
vim.keymap.set("n", "<c-o>", rulelib.ts_picker(), { desc = "TS outline (overview)" })
vim.keymap.set("n", "<c-r>", builtin.live_grep, { desc = "Live grep" })
vim.keymap.set("n", "<c-b>", builtin.buffers, { desc = "Buffers" })
vim.keymap.set("n", "<c-h>", harpoon_ui.toggle_quick_menu, { desc = "Harpoon" })
vim.keymap.set("n", "<c-a>", require("harpoon.mark").add_file, { desc = "Harpoon Add" })
vim.keymap.set("n", "<leader>fh", builtin.help_tags, { desc = "Help" })
vim.keymap.set("n", "<leader>fr", builtin.oldfiles, { desc = "Recent files" })
--vim.keymap.set("n", "<c-f>", builtin.find_files, { desc = "find files" })
vim.keymap.set("n", "<c-f>", function()
	require("fff").find_files()
end, { desc = "FFFind files" })
vim.keymap.set("n", "<leader>z", function()
	require("zen-mode").toggle()
end, { desc = "Toggle Zen Mode" })

vim.keymap.set("n", "<leader>tw", function()
	require("twilight").toggle()
end, { desc = "Toggle Twilight" })

vim.keymap.set("n", "<leader>sw", function()
	vim.opt_local.spell = not vim.opt_local.spell:get()
end, { desc = "Toggle spellcheck" })

vim.api.nvim_create_user_command("WordCount", function()
	local wc = vim.fn.wordcount()
	print("Words: " .. wc.words)
end, {})
